/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleRouteRouteImport } from './routes/$locale/route'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleDiscoverRouteImport } from './routes/$locale/discover'
import { Route as LocaleHowItWorksRouteImport } from './routes/$locale/how-it-works'
import { Route as LocaleMostRequestedRouteImport } from './routes/$locale/most-requested'
import { Route as LocalePoliciesRouteImport } from './routes/$locale/policies'
import { Route as LocaleReviewsRouteImport } from './routes/$locale/reviews'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRouteRoute = LocaleRouteRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleDiscoverRoute = LocaleDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleHowItWorksRoute = LocaleHowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleMostRequestedRoute = LocaleMostRequestedRouteImport.update({
  id: '/most-requested',
  path: '/most-requested',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocalePoliciesRoute = LocalePoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleReviewsRoute = LocaleReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => LocaleRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/$locale/discover': typeof LocaleDiscoverRoute
  '/$locale/how-it-works': typeof LocaleHowItWorksRoute
  '/$locale/most-requested': typeof LocaleMostRequestedRoute
  '/$locale/policies': typeof LocalePoliciesRoute
  '/$locale/reviews': typeof LocaleReviewsRoute
  '/$locale/': typeof LocaleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale/discover': typeof LocaleDiscoverRoute
  '/$locale/how-it-works': typeof LocaleHowItWorksRoute
  '/$locale/most-requested': typeof LocaleMostRequestedRoute
  '/$locale/policies': typeof LocalePoliciesRoute
  '/$locale/reviews': typeof LocaleReviewsRoute
  '/$locale': typeof LocaleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/$locale/discover': typeof LocaleDiscoverRoute
  '/$locale/how-it-works': typeof LocaleHowItWorksRoute
  '/$locale/most-requested': typeof LocaleMostRequestedRoute
  '/$locale/policies': typeof LocalePoliciesRoute
  '/$locale/reviews': typeof LocaleReviewsRoute
  '/$locale/': typeof LocaleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/discover'
    | '/$locale/how-it-works'
    | '/$locale/most-requested'
    | '/$locale/policies'
    | '/$locale/reviews'
    | '/$locale/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale/discover'
    | '/$locale/how-it-works'
    | '/$locale/most-requested'
    | '/$locale/policies'
    | '/$locale/reviews'
    | '/$locale'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/discover'
    | '/$locale/how-it-works'
    | '/$locale/most-requested'
    | '/$locale/policies'
    | '/$locale/reviews'
    | '/$locale/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRouteRoute: typeof LocaleRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/discover': {
      id: '/$locale/discover'
      path: '/discover'
      fullPath: '/$locale/discover'
      preLoaderRoute: typeof LocaleDiscoverRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/how-it-works': {
      id: '/$locale/how-it-works'
      path: '/how-it-works'
      fullPath: '/$locale/how-it-works'
      preLoaderRoute: typeof LocaleHowItWorksRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/most-requested': {
      id: '/$locale/most-requested'
      path: '/most-requested'
      fullPath: '/$locale/most-requested'
      preLoaderRoute: typeof LocaleMostRequestedRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/policies': {
      id: '/$locale/policies'
      path: '/policies'
      fullPath: '/$locale/policies'
      preLoaderRoute: typeof LocalePoliciesRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/reviews': {
      id: '/$locale/reviews'
      path: '/reviews'
      fullPath: '/$locale/reviews'
      preLoaderRoute: typeof LocaleReviewsRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
  }
}

interface LocaleRouteRouteChildren {
  LocaleDiscoverRoute: typeof LocaleDiscoverRoute
  LocaleHowItWorksRoute: typeof LocaleHowItWorksRoute
  LocaleMostRequestedRoute: typeof LocaleMostRequestedRoute
  LocalePoliciesRoute: typeof LocalePoliciesRoute
  LocaleReviewsRoute: typeof LocaleReviewsRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
}

const LocaleRouteRouteChildren: LocaleRouteRouteChildren = {
  LocaleDiscoverRoute: LocaleDiscoverRoute,
  LocaleHowItWorksRoute: LocaleHowItWorksRoute,
  LocaleMostRequestedRoute: LocaleMostRequestedRoute,
  LocalePoliciesRoute: LocalePoliciesRoute,
  LocaleReviewsRoute: LocaleReviewsRoute,
  LocaleIndexRoute: LocaleIndexRoute,
}

const LocaleRouteRouteWithChildren = LocaleRouteRoute._addFileChildren(
  LocaleRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRouteRoute: LocaleRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
